In [2]:
import pandas as pd
import numpy as np

# Create a Pandas dataframe. Loading from HDF5
price_data = pd.read_hdf(
    '../tests/data/prices.hd5', index_col='time')

In [3]:
# get all close prices from the dataframe price_data from column close for all symbols via loc
close_cols1 = price_data.loc[:, price_data.columns.get_level_values(1) == 'open']
close_cols1

symbol               BTCUSDT EOSUSD   ETHUSD LTCUSDT  XRPUSD
candle_info             open   open     open    open    open
open_time
2020-10-01 00:00:00  10759.0  2.578   359.85     NaN  0.2416
2020-10-01 00:30:00  10790.0  2.581   358.95     NaN  0.2416
2020-10-01 01:00:00  10777.0  2.582   359.25     NaN  0.2418
2020-10-01 01:30:00  10793.0  2.588   359.75     NaN  0.2418
2020-10-01 02:00:00  10822.0  2.591   361.20     NaN  0.2424
...                      ...    ...      ...     ...     ...
2021-04-14 21:30:00  62703.5  7.582  2406.20  269.26  1.7818
2021-04-14 22:00:00  62795.0  7.610  2434.05  280.82  1.8181
2021-04-14 22:30:00  62680.0  7.654  2427.00  278.49  1.7827
2021-04-14 23:00:00  62849.5  7.708  2431.30  277.50  1.7995
2021-04-14 23:30:00  62999.0  7.776  2445.95  279.05  1.8301

[9408 rows x 5 columns]

In [5]:
price_data

symbol               BTCUSDT                            EOSUSD                \
candle_info             open     high      low    close   open   high    low
open_time
2020-10-01 00:00:00  10759.0  10817.5  10759.0  10790.0  2.578  2.584  2.578
2020-10-01 00:30:00  10790.0  10790.5  10775.0  10777.0  2.581  2.583  2.579
2020-10-01 01:00:00  10777.0  10793.0  10777.0  10793.0  2.582  2.588  2.580
2020-10-01 01:30:00  10793.0  10836.0  10792.5  10822.0  2.588  2.592  2.587
2020-10-01 02:00:00  10822.0  10841.5  10808.0  10808.5  2.591  2.597  2.591
...                      ...      ...      ...      ...    ...    ...    ...
2021-04-14 21:30:00  62703.5  62812.5  62615.5  62795.0  7.582  7.620  7.537
2021-04-14 22:00:00  62795.0  62825.0  62591.0  62680.0  7.610  7.728  7.552
2021-04-14 22:30:00  62680.0  62993.0  62680.0  62849.5  7.654  7.770  7.654
2021-04-14 23:00:00  62849.5  62999.0  62750.0  62999.0  7.708  7.787  7.670
2021-04-14 23:30:00  62999.0  62999.0  62606.0  62921.0  7.776  7.776  7.626

symbol                       ETHUSD                            LTCUSDT  \
candle_info          close     open     high      low    close    open
open_time
2020-10-01 00:00:00  2.581   359.85   361.45   358.85   358.95     NaN
2020-10-01 00:30:00  2.582   358.95   359.75   358.95   359.25     NaN
2020-10-01 01:00:00  2.588   359.25   359.80   358.80   359.75     NaN
2020-10-01 01:30:00  2.591   359.75   361.40   359.75   361.20     NaN
2020-10-01 02:00:00  2.592   361.20   364.05   361.20   362.95     NaN
...                    ...      ...      ...      ...      ...     ...
2021-04-14 21:30:00  7.610  2406.20  2440.00  2397.20  2434.05  269.26
2021-04-14 22:00:00  7.654  2434.05  2445.00  2418.65  2427.00  280.82
2021-04-14 22:30:00  7.708  2427.00  2438.60  2423.50  2431.30  278.49
2021-04-14 23:00:00  7.776  2431.30  2450.00  2431.30  2445.95  277.50
2021-04-14 23:30:00  7.680  2445.95  2445.95  2417.40  2438.20  279.05

symbol                                       XRPUSD
candle_info            high     low   close    open    high     low   close
open_time
2020-10-01 00:00:00     NaN     NaN     NaN  0.2416  0.2424  0.2416  0.2416
2020-10-01 00:30:00     NaN     NaN     NaN  0.2416  0.2419  0.2415  0.2418
2020-10-01 01:00:00     NaN     NaN     NaN  0.2418  0.2420  0.2415  0.2418
2020-10-01 01:30:00     NaN     NaN     NaN  0.2418  0.2426  0.2417  0.2424
2020-10-01 02:00:00     NaN     NaN     NaN  0.2424  0.2431  0.2423  0.2424
...                     ...     ...     ...     ...     ...     ...     ...
2021-04-14 21:30:00  281.37  269.11  280.82  1.7818  1.8247  1.7738  1.8181
2021-04-14 22:00:00  282.02  278.24  278.49  1.8181  1.8185  1.7701  1.7827
2021-04-14 22:30:00  281.31  276.64  277.50  1.7827  1.8179  1.7827  1.7995
2021-04-14 23:00:00  280.17  277.46  279.05  1.7995  1.8415  1.7915  1.8301
2021-04-14 23:30:00  280.95  277.95  279.41  1.8301  1.8547  1.8195  1.8391

[9408 rows x 20 columns]

In [6]:
price_data.columns

MultiIndex([('BTCUSDT',  'open'),
            ('BTCUSDT',  'high'),
            ('BTCUSDT',   'low'),
            ('BTCUSDT', 'close'),
            ( 'EOSUSD',  'open'),
            ( 'EOSUSD',  'high'),
            ( 'EOSUSD',   'low'),
            ( 'EOSUSD', 'close'),
            ( 'ETHUSD',  'open'),
            ( 'ETHUSD',  'high'),
            ( 'ETHUSD',   'low'),
            ( 'ETHUSD', 'close'),
            ('LTCUSDT',  'open'),
            ('LTCUSDT',  'high'),
            ('LTCUSDT',   'low'),
            ('LTCUSDT', 'close'),
            ( 'XRPUSD',  'open'),
            ( 'XRPUSD',  'high'),
            ( 'XRPUSD',   'low'),
            ( 'XRPUSD', 'close')],
           names=['symbol', 'candle_info'])

In [4]:
price_data[[('BTCUSDT',  'open')]]

symbol               BTCUSDT
candle_info             open
open_time
2020-10-01 00:00:00  10759.0
2020-10-01 00:30:00  10790.0
2020-10-01 01:00:00  10777.0
2020-10-01 01:30:00  10793.0
2020-10-01 02:00:00  10822.0
...                      ...
2021-04-14 21:30:00  62703.5
2021-04-14 22:00:00  62795.0
2021-04-14 22:30:00  62680.0
2021-04-14 23:00:00  62849.5
2021-04-14 23:30:00  62999.0

[9408 rows x 1 columns]

In [26]:
price_data.columns

MultiIndex([('BTCUSDT',  'open'),
            ('BTCUSDT',  'high'),
            ('BTCUSDT',   'low'),
            ('BTCUSDT', 'close'),
            ( 'EOSUSD',  'open'),
            ( 'EOSUSD',  'high'),
            ( 'EOSUSD',   'low'),
            ( 'EOSUSD', 'close'),
            ( 'ETHUSD',  'open'),
            ( 'ETHUSD',  'high'),
            ( 'ETHUSD',   'low'),
            ( 'ETHUSD', 'close'),
            ('LTCUSDT',  'open'),
            ('LTCUSDT',  'high'),
            ('LTCUSDT',   'low'),
            ('LTCUSDT', 'close'),
            ( 'XRPUSD',  'open'),
            ( 'XRPUSD',  'high'),
            ( 'XRPUSD',   'low'),
            ( 'XRPUSD', 'close')],
           names=['symbol', 'candle_info'])

In [27]:
close_df_BTCUSDT = price_data['BTCUSDT']['close'].to_frame()
close_df_BTCUSDT

                       close
open_time
2020-10-01 00:00:00  10790.0
2020-10-01 00:30:00  10777.0
2020-10-01 01:00:00  10793.0
2020-10-01 01:30:00  10822.0
2020-10-01 02:00:00  10808.5
...                      ...
2021-04-14 21:30:00  62795.0
2021-04-14 22:00:00  62680.0
2021-04-14 22:30:00  62849.5
2021-04-14 23:00:00  62999.0
2021-04-14 23:30:00  62921.0

[9408 rows x 1 columns]