In [2]:
import quantfreedom as qf
import ccxt

In [13]:
exh = ccxt.bybit()

In [ ]:
exh.load_markets()

In [ ]:
exh.symbols

In [19]:
qf.CCXTData.data_download(
    exchange='bybit',
    start='2023-01-01T00:00:00Z',
    end='2023-02-01T00:00:00Z',
    symbol='BTCUSDT',
    timeframe='4h'
)

                         open      high       low     close    volume
open_time
2023-01-01 00:00:00 16,549.50 16,577.50 16,524.00 16,553.00  3,395.49
2023-01-01 04:00:00 16,553.00 16,560.00 16,511.00 16,537.50  3,838.74
2023-01-01 08:00:00 16,537.50 16,569.00 16,519.00 16,568.50  3,559.73
2023-01-01 12:00:00 16,568.50 16,582.00 16,550.50 16,574.00  3,960.76
2023-01-01 16:00:00 16,574.00 16,631.00 16,569.50 16,608.00  6,533.61
...                       ...       ...       ...       ...       ...
2023-01-31 04:00:00 22,830.50 22,986.50 22,734.50 22,970.50 12,183.56
2023-01-31 08:00:00 22,970.50 22,994.00 22,801.00 22,855.50 11,930.56
2023-01-31 12:00:00 22,855.50 23,214.00 22,848.00 23,115.00 32,948.55
2023-01-31 16:00:00 23,115.00 23,224.50 23,076.00 23,160.00 12,801.34
2023-01-31 20:00:00 23,160.00 23,375.00 22,801.50 23,130.00 35,444.94

[186 rows x 5 columns]