In [1]:
import quantfreedom as qf
import pandas as pd

In [2]:
price_data = pd.read_hdf('data/prices.hd5')
price_data

symbol                BTCUSDT                               EOSUSD
candle_info              open      high       low     close   open high  low
open_time
2020-10-01 00:00:00 10,759.00 10,817.50 10,759.00 10,790.00   2.58 2.58 2.58  \
2020-10-01 00:30:00 10,790.00 10,790.50 10,775.00 10,777.00   2.58 2.58 2.58
2020-10-01 01:00:00 10,777.00 10,793.00 10,777.00 10,793.00   2.58 2.59 2.58
2020-10-01 01:30:00 10,793.00 10,836.00 10,792.50 10,822.00   2.59 2.59 2.59
2020-10-01 02:00:00 10,822.00 10,841.50 10,808.00 10,808.50   2.59 2.60 2.59
...                       ...       ...       ...       ...    ...  ...  ...
2021-04-14 21:30:00 62,703.50 62,812.50 62,615.50 62,795.00   7.58 7.62 7.54
2021-04-14 22:00:00 62,795.00 62,825.00 62,591.00 62,680.00   7.61 7.73 7.55
2021-04-14 22:30:00 62,680.00 62,993.00 62,680.00 62,849.50   7.65 7.77 7.65
2021-04-14 23:00:00 62,849.50 62,999.00 62,750.00 62,999.00   7.71 7.79 7.67
2021-04-14 23:30:00 62,999.00 62,999.00 62,606.00 62,921.00   7.78 7.78 7.63

symbol                      ETHUSD                            LTCUSDT
candle_info         close     open     high      low    close    open   high
open_time
2020-10-01 00:00:00  2.58   359.85   361.45   358.85   358.95     NaN    NaN  \
2020-10-01 00:30:00  2.58   358.95   359.75   358.95   359.25     NaN    NaN
2020-10-01 01:00:00  2.59   359.25   359.80   358.80   359.75     NaN    NaN
2020-10-01 01:30:00  2.59   359.75   361.40   359.75   361.20     NaN    NaN
2020-10-01 02:00:00  2.59   361.20   364.05   361.20   362.95     NaN    NaN
...                   ...      ...      ...      ...      ...     ...    ...
2021-04-14 21:30:00  7.61 2,406.20 2,440.00 2,397.20 2,434.05  269.26 281.37
2021-04-14 22:00:00  7.65 2,434.05 2,445.00 2,418.65 2,427.00  280.82 282.02
2021-04-14 22:30:00  7.71 2,427.00 2,438.60 2,423.50 2,431.30  278.49 281.31
2021-04-14 23:00:00  7.78 2,431.30 2,450.00 2,431.30 2,445.95  277.50 280.17
2021-04-14 23:30:00  7.68 2,445.95 2,445.95 2,417.40 2,438.20  279.05 280.95

symbol                            XRPUSD
candle_info            low  close   open high  low close
open_time
2020-10-01 00:00:00    NaN    NaN   0.24 0.24 0.24  0.24
2020-10-01 00:30:00    NaN    NaN   0.24 0.24 0.24  0.24
2020-10-01 01:00:00    NaN    NaN   0.24 0.24 0.24  0.24
2020-10-01 01:30:00    NaN    NaN   0.24 0.24 0.24  0.24
2020-10-01 02:00:00    NaN    NaN   0.24 0.24 0.24  0.24
...                    ...    ...    ...  ...  ...   ...
2021-04-14 21:30:00 269.11 280.82   1.78 1.82 1.77  1.82
2021-04-14 22:00:00 278.24 278.49   1.82 1.82 1.77  1.78
2021-04-14 22:30:00 276.64 277.50   1.78 1.82 1.78  1.80
2021-04-14 23:00:00 277.46 279.05   1.80 1.84 1.79  1.83
2021-04-14 23:30:00 277.95 279.41   1.83 1.85 1.82  1.84

[9408 rows x 20 columns]

In [4]:
btc_prices = pd.DataFrame().join(price_data[['BTCUSDT']])
btc_prices

MergeError: Not allowed to merge between different levels. (1 levels on the left, 2 on the right)

In [112]:
price_data[price_data['BTCUSDT'] == price_data['BTCUSDT']]

symbol                BTCUSDT                               EOSUSD            \
candle_info              open      high       low     close   open high  low
open_time
2020-10-01 00:00:00 10,759.00 10,817.50 10,759.00 10,790.00   2.58 2.58 2.58
2020-10-01 00:30:00 10,790.00 10,790.50 10,775.00 10,777.00   2.58 2.58 2.58
2020-10-01 01:00:00 10,777.00 10,793.00 10,777.00 10,793.00   2.58 2.59 2.58
2020-10-01 01:30:00 10,793.00 10,836.00 10,792.50 10,822.00   2.59 2.59 2.59
2020-10-01 02:00:00 10,822.00 10,841.50 10,808.00 10,808.50   2.59 2.60 2.59
...                       ...       ...       ...       ...    ...  ...  ...
2021-04-14 21:30:00 62,703.50 62,812.50 62,615.50 62,795.00   7.58 7.62 7.54
2021-04-14 22:00:00 62,795.00 62,825.00 62,591.00 62,680.00   7.61 7.73 7.55
2021-04-14 22:30:00 62,680.00 62,993.00 62,680.00 62,849.50   7.65 7.77 7.65
2021-04-14 23:00:00 62,849.50 62,999.00 62,750.00 62,999.00   7.71 7.79 7.67
2021-04-14 23:30:00 62,999.00 62,999.00 62,606.00 62,921.00   7.78 7.78 7.63

symbol                      ETHUSD                            LTCUSDT         \
candle_info         close     open     high      low    close    open   high
open_time
2020-10-01 00:00:00  2.58   359.85   361.45   358.85   358.95     NaN    NaN
2020-10-01 00:30:00  2.58   358.95   359.75   358.95   359.25     NaN    NaN
2020-10-01 01:00:00  2.59   359.25   359.80   358.80   359.75     NaN    NaN
2020-10-01 01:30:00  2.59   359.75   361.40   359.75   361.20     NaN    NaN
2020-10-01 02:00:00  2.59   361.20   364.05   361.20   362.95     NaN    NaN
...                   ...      ...      ...      ...      ...     ...    ...
2021-04-14 21:30:00  7.61 2,406.20 2,440.00 2,397.20 2,434.05  269.26 281.37
2021-04-14 22:00:00  7.65 2,434.05 2,445.00 2,418.65 2,427.00  280.82 282.02
2021-04-14 22:30:00  7.71 2,427.00 2,438.60 2,423.50 2,431.30  278.49 281.31
2021-04-14 23:00:00  7.78 2,431.30 2,450.00 2,431.30 2,445.95  277.50 280.17
2021-04-14 23:30:00  7.68 2,445.95 2,445.95 2,417.40 2,438.20  279.05 280.95

symbol                            XRPUSD
candle_info            low  close   open high  low close
open_time
2020-10-01 00:00:00    NaN    NaN   0.24 0.24 0.24  0.24
2020-10-01 00:30:00    NaN    NaN   0.24 0.24 0.24  0.24
2020-10-01 01:00:00    NaN    NaN   0.24 0.24 0.24  0.24
2020-10-01 01:30:00    NaN    NaN   0.24 0.24 0.24  0.24
2020-10-01 02:00:00    NaN    NaN   0.24 0.24 0.24  0.24
...                    ...    ...    ...  ...  ...   ...
2021-04-14 21:30:00 269.11 280.82   1.78 1.82 1.77  1.82
2021-04-14 22:00:00 278.24 278.49   1.82 1.82 1.77  1.78
2021-04-14 22:30:00 276.64 277.50   1.78 1.82 1.78  1.80
2021-04-14 23:00:00 277.46 279.05   1.80 1.84 1.79  1.83
2021-04-14 23:30:00 277.95 279.41   1.83 1.85 1.82  1.84

[9408 rows x 20 columns]

In [105]:
price_data.copy()

symbol              EOSUSD                   ETHUSD                    \
candle_info           open high  low close     open     high      low
open_time
2020-10-01 00:00:00   2.58 2.58 2.58  2.58   359.85   361.45   358.85
2020-10-01 00:30:00   2.58 2.58 2.58  2.58   358.95   359.75   358.95
2020-10-01 01:00:00   2.58 2.59 2.58  2.59   359.25   359.80   358.80
2020-10-01 01:30:00   2.59 2.59 2.59  2.59   359.75   361.40   359.75
2020-10-01 02:00:00   2.59 2.60 2.59  2.59   361.20   364.05   361.20
...                    ...  ...  ...   ...      ...      ...      ...
2021-04-14 21:30:00   7.58 7.62 7.54  7.61 2,406.20 2,440.00 2,397.20
2021-04-14 22:00:00   7.61 7.73 7.55  7.65 2,434.05 2,445.00 2,418.65
2021-04-14 22:30:00   7.65 7.77 7.65  7.71 2,427.00 2,438.60 2,423.50
2021-04-14 23:00:00   7.71 7.79 7.67  7.78 2,431.30 2,450.00 2,431.30
2021-04-14 23:30:00   7.78 7.78 7.63  7.68 2,445.95 2,445.95 2,417.40

symbol                       LTCUSDT                      XRPUSD            \
candle_info            close    open   high    low  close   open high  low
open_time
2020-10-01 00:00:00   358.95     NaN    NaN    NaN    NaN   0.24 0.24 0.24
2020-10-01 00:30:00   359.25     NaN    NaN    NaN    NaN   0.24 0.24 0.24
2020-10-01 01:00:00   359.75     NaN    NaN    NaN    NaN   0.24 0.24 0.24
2020-10-01 01:30:00   361.20     NaN    NaN    NaN    NaN   0.24 0.24 0.24
2020-10-01 02:00:00   362.95     NaN    NaN    NaN    NaN   0.24 0.24 0.24
...                      ...     ...    ...    ...    ...    ...  ...  ...
2021-04-14 21:30:00 2,434.05  269.26 281.37 269.11 280.82   1.78 1.82 1.77
2021-04-14 22:00:00 2,427.00  280.82 282.02 278.24 278.49   1.82 1.82 1.77
2021-04-14 22:30:00 2,431.30  278.49 281.31 276.64 277.50   1.78 1.82 1.78
2021-04-14 23:00:00 2,445.95  277.50 280.17 277.46 279.05   1.80 1.84 1.79
2021-04-14 23:30:00 2,438.20  279.05 280.95 277.95 279.41   1.83 1.85 1.82

symbol
candle_info         close
open_time
2020-10-01 00:00:00  0.24
2020-10-01 00:30:00  0.24
2020-10-01 01:00:00  0.24
2020-10-01 01:30:00  0.24
2020-10-01 02:00:00  0.24
...                   ...
2021-04-14 21:30:00  1.82
2021-04-14 22:00:00  1.78
2021-04-14 22:30:00  1.80
2021-04-14 23:00:00  1.83
2021-04-14 23:30:00  1.84

[9408 rows x 16 columns]

In [42]:
price_data.columns.levels

FrozenList([['BTCUSDT', 'EOSUSD', 'ETHUSD', 'LTCUSDT', 'XRPUSD'], ['close', 'high', 'low', 'open']])

In [4]:
qf.from_talib(
    func_name="rsi",
    price_data=price_data,
    timeperiod=20,
    plot_results=False,
    # price="low",
)

KeyError: 'EOSUSD'